ARG VERSION=trixie
ARG TYPE=base
FROM wpilib/debian-${TYPE}:${VERSION}

# Install toolchain
RUN curl -SL https://github.com/wpilibsuite/opensdk/releases/download/v2025-2/arm64-bookworm-2025-x86_64-linux-gnu-Toolchain-12.2.0.tgz | sh -c 'mkdir -p /usr/local && cd /usr/local && tar xzf - --strip-components=2'

RUN apt update && apt install -y avahi-daemon && rm -rf /var/lib/apt/lists/*

WORKDIR /
