ARG UBUNTU=22.04
ARG TYPE=base
FROM wpilib/ubuntu-${TYPE}:${UBUNTU}

# Install toolchain
RUN curl -SL https://github.com/wpilibsuite/opensdk/releases/download/v2025-1/arm64-bullseye-2025-x86_64-linux-gnu-Toolchain-10.2.0.tgz | sh -c 'mkdir -p /usr/local && cd /usr/local && tar xzf - --strip-components=2'

WORKDIR /
