ARG UBUNTU=20.04
FROM wpilib/ubuntu-base:${UBUNTU}

# Install toolchain
RUN curl -SL https://github.com/wpilibsuite/raspbian-toolchain/releases/download/v2.1.0/Raspbian10-Linux-Toolchain-8.3.0.tar.gz | sh -c 'mkdir -p /usr/local && cd /usr/local && tar xzf - --strip-components=1'

WORKDIR /
